### ISSUE TITLE
Not working in docker-compose

### ISSUE THREAD

**Issue by jdekarske** [securisec/code-traefikode#3]
Hi! I hope this project isn't abandoned. I was looking forward to using it, but it doesn't seem to work in my docker-compose configuration.  I tried both cli and 'traefik' triggers with no response. I don't see any relevant errors in the developer tools console or the output console so I'm not sure how to troubleshoot.

**Comment by securisec** [comment]
Thank you for bringing this issue to my attention @jdekarske . After debugging the extension for a bit, it seems that the some changes introduced to how vscode handles yaml files have changed on more recent versions that breaks this extension (the extension was a WIP from about 2 years ago). I dont have the bandwidth atm to update for the breaking changes, so I deprecated this extension from the marketplace. The `traefik.yaml` file intellisense still works because it uses json schema.
